version: "3.8"

services:
  redis:
      image: redis:7.2
          ports:
                - "6379:6379"

                  backend:
                      build: .
                          command: uvicorn app.main:app --host 0.0.0.0 --port 8000
                              environment:
                                    - NVIDIA_VISIBLE_DEVICES=all
                                          - CUDA_VISIBLE_DEVICES=0
                                                - MODEL_TYPE=${MODEL_TYPE}
                                                      - MODEL_ID=${MODEL_ID}
                                                            - REDIS_URL=${REDIS_URL}
                                                                volumes:
                                                                      - ./outputs:/app/outputs
                                                                          ports:
                                                                                - "8000:8000"
                                                                                    depends_on:
                                                                                          - redis
                                                                                              deploy:
                                                                                                    resources:
                                                                                                            reservations:
                                                                                                                      devices:
                                                                                                                                  - capabilities: [gpu]

                                                                                                                                    worker:
                                                                                                                                        build: .
                                                                                                                                            command: celery -A app.workers.tasks.celery worker --loglevel=INFO
                                                                                                                                                environment:
                                                                                                                                                      - NVIDIA_VISIBLE_DEVICES=all
                                                                                                                                                            - CUDA_VISIBLE_DEVICES=0
                                                                                                                                                                  - MODEL_TYPE=${MODEL_TYPE}
                                                                                                                                                                        - MODEL_ID=${MODEL_ID}
                                                                                                                                                                              - REDIS_URL=${REDIS_URL}
                                                                                                                                                                                  depends_on:
                                                                                                                                                                                        - redis
                                                                                                                                                                                            volumes:
                                                                                                                                                                                                  - ./outputs:/app/outputs
                                                                                                                                                                                                      deploy:
                                                                                                                                                                                                            resources:
                                                                                                                                                                                                                    reservations:
                                                                                                                                                                                                                              devices:
                                                                                                                                                                                                                                          - capabilities: [gpu]